services:
  - type: web
    name: auxiliar-legislativo
    env: python
    plan: free
    rootDir: agent_workspace
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main_fastapi:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DATASUS_LOGIN
        sync: false
      - key: DATASUS_PASSWORD
        sync: false
      - key: TRANSPARENCIA_API_KEY
        sync: false
