metadata:
  name: Sistema de Buscas APIs Oficiais BR
  version: 2.0.0-consolidado
  description: Sistema integrado de buscas utilizando exclusivamente APIs oficiais
    do governo brasileiro - Versão consolidada e corrigida
  author: Sérgio
  created_date: '2025-09-09'
  last_updated: '2025-09-09'
  documentation: Baseado nas documentações oficiais de cada API consultadas em 09/09/2025
  test_results:
    tested_date: '2025-09-09'
    total_apis: 7
    functional_apis: 6
    success_rate: 85.7%
    notes: Portal da Transparência corrigido, ANEEL removida, configurações validadas
system:
  environment: development
  debug: true
  log_level: INFO
  timeout: 30
  max_retries: 3
  rate_limit: 100
  cache_enabled: true
  cache_ttl: 3600
apis:
  portal_transparencia:
    name: Portal da Transparência
    base_url: https://api.portaldatransparencia.gov.br/api-de-dados
    enabled: true
    token_required: true
    token_header: chave-api-dados
    rate_limit:
      requests_per_minute: 90
      requests_per_minute_off_peak: 300
      burst_limit: 100
    endpoints:
    - path: /despesas/por-orgao
      method: GET
      description: Consulta despesas por órgão
      parameters:
      - codigoOrgao
      - dataInicio
      - dataFim
      - pagina
      - itensPorPagina
    - path: /despesas/por-funcional-programatica
      method: GET
      description: Despesas por classificação funcional
      parameters:
      - codigoFuncional
      - dataInicio
      - dataFim
    - path: /despesas/recursos-recebidos
      method: GET
      description: Recursos recebidos por favorecido
    - path: /despesas/tipo-transferencia
      method: GET
      description: Tipos de transferência
    - path: /servidores
      method: GET
      description: Servidores do Poder Executivo
      parameters:
      - pagina
      - itensPorPagina
    - path: /servidores/{id}
      method: GET
      description: Consulta servidor por ID
      parameters:
      - id
    - path: /servidores/remuneracao
      method: GET
      description: Remunerações de servidor
      parameters:
      - cpf
      - id
      - mes
      - ano
    - path: /servidores/por-orgao
      method: GET
      description: Servidores por órgão
      parameters:
      - codigoOrgao
      - mes
      - ano
      - pagina
      - itensPorPagina
    - path: /servidores/funcoes-e-cargos
      method: GET
      description: Funções e cargos de confiança
    - path: /viagens
      method: GET
      description: Consulta viagens por período
      parameters:
      - dataInicio
      - dataFim
      - pagina
      - itensPorPagina
    - path: /viagens/{id}
      method: GET
      description: Consulta viagem por ID
      parameters:
      - id
    - path: /viagens-por-cpf
      method: GET
      description: Viagens por CPF
      parameters:
      - cpf
      - dataInicio
      - dataFim
    - path: /orgaos-siafi
      method: GET
      description: Lista órgãos SIAFI
    - path: /orgaos-siape
      method: GET
      description: Lista órgãos SIAPE
    - path: /licitacoes
      method: GET
      description: Todas as licitações
    - path: /licitacoes/{id}
      method: GET
      description: Licitação por ID
      parameters:
      - id
    - path: /licitacoes/modalidades
      method: GET
      description: Modalidades de licitação
    - path: /novo-bolsa-familia-por-municipio
      method: GET
      description: Bolsa Família por município
      parameters:
      - codigoMunicipio
      - mes
      - ano
    - path: /bpc-por-municipio
      method: GET
      description: BPC por município
      parameters:
      - codigoMunicipio
      - mes
      - ano
    - path: /auxilio-emergencial-por-municipio
      method: GET
      description: Auxílio emergencial por município
      parameters:
      - codigoMunicipio
      - mes
      - ano
    - path: /pessoa-fisica
      method: GET
      description: Consulta pessoas físicas
    - path: /pessoa-juridica
      method: GET
      description: Consulta pessoas jurídicas
    - path: /peps
      method: GET
      description: Consulta PEPs
      parameters:
      - nome
      - cpfCnpj
    auth_note: Status 401 esperado sem token - Configure PORTAL_TRANSPARENCIA_API_KEY
  brasil_api:
    name: Brasil API
    base_url: https://brasilapi.com.br/api
    enabled: true
    token_required: false
    rate_limit:
      requests_per_minute: 200
      burst_limit: 50
    endpoints:
    - path: /cep/v1/{cep}
      method: GET
      description: Consulta CEP
      parameters:
      - cep
    - path: /cep/v2/{cep}
      method: GET
      description: Consulta CEP v2
      parameters:
      - cep
    - path: /cnpj/v1/{cnpj}
      method: GET
      description: Consulta CNPJ
      parameters:
      - cnpj
    - path: /banks/v1
      method: GET
      description: Lista bancos brasileiros
    - path: /banks/v1
      method: GET
      description: Lista bancos brasileiros
    - path: /taxas/v1
      method: GET
      description: Taxas de juros e inflação
    - path: /ddd/v1/{ddd}
      method: GET
      description: Cidades por DDD
      parameters:
      - ddd
    - path: /ibge/municipios/v1/{uf}
      method: GET
      description: Municípios por UF
      parameters:
      - uf
    - path: /ibge/uf/v1
      method: GET
      description: Lista estados brasileiros
    - path: /feriados/v1/{ano}
      method: GET
      description: Feriados nacionais
      parameters:
      - ano
    - path: /isbn/v1/{isbn}
      method: GET
      description: Dados de livro por ISBN
      parameters:
      - isbn
    - path: /pix/v1/participants
      method: GET
      description: Participantes do PIX
  camara_deputados:
    name: API Câmara dos Deputados
    base_url: https://dadosabertos.camara.leg.br/api/v2
    enabled: true
    token_required: false
    rate_limit:
      requests_per_minute: 120
      burst_limit: 30
    endpoints:
    - path: /deputados
      method: GET
      description: Lista deputados
      parameters:
      - nome
      - siglaUf
      - siglaPartido
      - siglaSexo
      - pagina
      - itens
    - path: /deputados/{id}
      method: GET
      description: Deputado por ID
      parameters:
      - id
    - path: /deputados/{id}/despesas
      method: GET
      description: Despesas de deputado
      parameters:
      - id
      - ano
      - mes
      - cnpjCpfFornecedor
    - path: /deputados/{id}/discursos
      method: GET
      description: Discursos de deputado
      parameters:
      - id
      - dataInicio
      - dataFim
    - path: /proposicoes
      method: GET
      description: Lista proposições
      parameters:
      - keywords
      - dataInicio
      - dataFim
      - autor
      - partido
    - path: /proposicoes/{id}
      method: GET
      description: Proposição por ID
      parameters:
      - id
    - path: /votacoes
      method: GET
      description: Lista votações
      parameters:
      - dataInicio
      - dataFim
      - pagina
      - itens
    - path: /votacoes/{id}
      method: GET
      description: Votação por ID
      parameters:
      - id
    - path: /partidos
      method: GET
      description: Lista partidos
    - path: /orgaos
      method: GET
      description: Lista órgãos da Câmara
  senado_federal:
    name: API Senado Federal
    base_url: https://legis.senado.leg.br/dadosabertos
    enabled: true
    token_required: false
    rate_limit:
      requests_per_minute: 100
      burst_limit: 25
    endpoints:
    - path: /senador/lista/atual
      method: GET
      description: Senadores em exercício
    - path: /senador/{codigoParlamentar}
      method: GET
      description: Senador por código
      parameters:
      - codigoParlamentar
    - path: /senador/{codigoParlamentar}/votacoes
      method: GET
      description: Votações de senador
      parameters:
      - codigoParlamentar
      - ano
    - path: /materia/{codigoMateria}
      method: GET
      description: Matéria por código
      parameters:
      - codigoMateria
    - path: /materia/atualizadas
      method: GET
      description: Matérias atualizadas
      parameters:
      - numdias
      - sigla
      - numero
      - ano
    - path: /comissao/lista/{tipo}
      method: GET
      description: Lista comissões
      parameters:
      - tipo
    - path: /plenario/lista/votacao/{data}
      method: GET
      description: Votações plenárias
      parameters:
      - data
    - path: /dados/ListaPartidos.xml
      method: GET
      description: Lista partidos (XML)
    - path: /legislacao/termos
      method: GET
      description: Termos de legislação
  dados_gov:
    name: Portal Brasileiro de Dados Abertos
    base_url: https://dados.gov.br/api/3
    enabled: true
    token_required: true
    token_header: Authorization
    token_prefix: Bearer
    rate_limit:
      requests_per_minute: 60
      burst_limit: 20
    endpoints:
    - path: /action/package_list
      method: GET
      description: Lista conjuntos de dados
    - path: /action/package_show
      method: GET
      description: Detalhes de conjunto
      parameters:
      - id
    - path: /action/package_search
      method: GET
      description: Busca conjuntos
      parameters:
      - q
      - rows
      - start
      - sort
    - path: /action/organization_list
      method: GET
      description: Lista organizações
    - path: /action/group_list
      method: GET
      description: Lista grupos/temas
    - path: /action/tag_list
      method: GET
      description: Lista tags
  ibge:
    name: API IBGE
    base_url: https://servicodados.ibge.gov.br/api/v1
    enabled: true
    token_required: false
    rate_limit:
      requests_per_minute: 200
      burst_limit: 50
    endpoints:
    - path: /localidades/estados
      method: GET
      description: Lista estados
      parameters:
      - orderBy
      - view
    - path: /localidades/estados/{uf}
      method: GET
      description: Estado por UF
      parameters:
      - uf
    - path: /localidades/municipios
      method: GET
      description: Lista municípios
      parameters:
      - UF
      - orderBy
      - view
    - path: /localidades/municipios/{id}
      method: GET
      description: Município por ID
      parameters:
      - id
    - path: /localidades/distritos
      method: GET
      description: Lista distritos
      parameters:
      - orderBy
      - view
    - path: /localidades/regioes
      method: GET
      description: Lista regiões
      parameters:
      - orderBy
      - view
    - path: /localidades/paises
      method: GET
      description: Lista países
      parameters:
      - orderBy
      - view
      - lang
    - path: /censos/nomes/ranking
      method: GET
      description: Ranking de nomes
      parameters:
      - nome
      - sexo
      - decada
    - path: /censos/nomes/{nome}
      method: GET
      description: Frequência de nome
      parameters:
      - nome
      - sexo
  banco_central:
    name: APIs Banco Central
    base_url: https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/odata
    enabled: true
    token_required: false
    rate_limit:
      requests_per_minute: 60
      burst_limit: 15
    endpoints:
    - path: /Moedas
      method: GET
      description: Lista moedas disponíveis
    - path: /CotacaoMoedaDia(moeda=@moeda,dataCotacao=@data)
      method: GET
      description: Cotação de moeda por data
      parameters:
      - moeda
      - data
      example: /CotacaoMoedaDia(moeda='USD',dataCotacao='2025-09-09')
    - path: /CotacaoMoedaPeriodo(moeda=@moeda,dataInicial=@dataInicial,dataFinalCotacao=@dataFinal)
      method: GET
      description: Cotações por período
      parameters:
      - moeda
      - dataInicial
      - dataFinal
      example: /CotacaoMoedaPeriodo(moeda='USD',dataInicial='2025-09-01',dataFinalCotacao='2025-09-09')
    alternative_endpoints:
      sgs: https://api.bcb.gov.br/dados/serie/bcdata.sgs
      pix: https://dadosabertos.bcb.gov.br/dataset/estatisticas-pix
authentication:
  portal_transparencia:
    type: api_key
    header: chave-api-dados
    env_var: PORTAL_TRANSPARENCIA_API_KEY
    registration_url: https://portaldatransparencia.gov.br/api-de-dados/cadastrar-email
  dados_gov:
    type: bearer_token
    header: Authorization
    env_var: DADOS_GOV_API_TOKEN
search_mapping:
  deputado:
  - camara_deputados
  senador:
  - senado_federal
  congresso:
  - camara_deputados
  - senado_federal
  lei:
  - camara_deputados
  - senado_federal
  proposicao:
  - camara_deputados
  - senado_federal
  votacao:
  - camara_deputados
  - senado_federal
  orcamento:
  - portal_transparencia
  despesa:
  - portal_transparencia
  gastos:
  - portal_transparencia
  servidor:
  - portal_transparencia
  licitacao:
  - portal_transparencia
  transparencia:
  - portal_transparencia
  cnpj:
  - brasil_api
  cep:
  - brasil_api
  ddd:
  - brasil_api
  municipio:
  - ibge
  - brasil_api
  estado:
  - ibge
  - brasil_api
  cidade:
  - ibge
  - brasil_api
  geografia:
  - ibge
  nome:
  - ibge
  banco:
  - brasil_api
  cotacao:
  - banco_central
  dolar:
  - banco_central
  cambio:
  - banco_central
  selic:
  - banco_central
  pix:
  - banco_central
  - brasil_api
  dados:
  - dados_gov
  dataset:
  - dados_gov
cache:
  type: redis
  host: localhost
  port: 6379
  db: 0
  prefix: api_search_
  default_ttl: 3600
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: logs/api_search.log
  max_size: 10MB
  backup_count: 5
web_interface:
  enabled: true
  host: 0.0.0.0
  port: 8000
  debug: false
  title: Sistema de Buscas - APIs Oficiais BR v2.0
  description: Interface consolidada para busca integrada em APIs governamentais brasileiras
export:
  formats:
  - json
  - csv
  - pdf
  max_results: 1000
  pdf_template: templates/report.html
monitoring:
  enabled: true
  metrics_endpoint: /metrics
  health_endpoint: /health
