# Configuração do Sistema de Buscas - APIs Oficiais Brasileiras
# Versão: 1.0.2-corrigido
# Data: 2025-09-09

metadata:
  name: "Sistema de Buscas APIs Oficiais BR"
  version: "1.0.2-corrigido"
  description: "Sistema integrado de buscas utilizando exclusivamente APIs oficiais do governo brasileiro"
  author: "Sérgio"
  created_date: "2025-09-09"
  last_updated: "2025-09-09"

system:
  environment: "development"
  debug: true
  log_level: "INFO"
  timeout: 30
  max_retries: 3
  rate_limit: 100
  cache_enabled: true
  cache_ttl: 3600

apis:
  dados_gov:
    name: "Portal Brasileiro de Dados Abertos"
    base_url: "https://dados.gov.br/api/3"
    enabled: true
    endpoints:
      - path: "/action/package_list"
        method: "GET"
        description: "Lista todos os conjuntos de dados"
      - path: "/action/package_show"
        method: "GET"
        description: "Detalhes de um conjunto específico"
        parameters: ["id"]
      - path: "/action/package_search"
        method: "GET"
        description: "Busca conjuntos de dados"
        parameters: ["q","rows","start"]

  brasil_api:
    name: "Brasil API"
    base_url: "https://brasilapi.com.br/api"
    enabled: true
    version: "v2"
    endpoints:
      - path: "/cep/v1/{cep}"
        method: "GET"
        description: "Consulta CEP"
        parameters: ["cep"]
      - path: "/cnpj/v1/{cnpj}"
        method: "GET"
        description: "Consulta CNPJ"
        parameters: ["cnpj"]
      - path: "/banks/v1"
        method: "GET"
        description: "Lista bancos"
      - path: "/taxas/v1"
        method: "GET"
        description: "Taxas de juros e inflação"

  receita_federal:
    name: "API Receita Federal"
    base_url: "https://www.receitaws.com.br/v1"
    enabled: true
    endpoints:
      - path: "/cnpj/{cnpj}"
        method: "GET"
        description: "Consulta dados de CNPJ"
        parameters: ["cnpj"]

  camara_deputados:
    name: "API Câmara dos Deputados"
    base_url: "https://dadosabertos.camara.leg.br/api/v2"
    enabled: true
    token_required: false
    endpoints:
      - path: "/deputados"
        method: "GET"
        description: "Lista deputados"
        parameters: ["nome","siglaUf","siglaPartido","siglaSexo"]
      - path: "/proposicoes"
        method: "GET"
        description: "Lista proposições"
        parameters: ["keywords","dataInicio","dataFim"]
      - path: "/votacoes"
        method: "GET"
        description: "Lista votações"
        parameters: ["dataInicio","dataFim"]

  senado_federal:
    name: "API Senado Federal"
    base_url: "https://legis.senado.leg.br/dadosabertos"
    enabled: true
    token_required: false
    endpoints:
      - path: "/senador/lista/atual"
        method: "GET"
        description: "Lista senadores em exercício"
      - path: "/senador/{codigoParlamentar}"
        method: "GET"
        description: "Detalha senador por código"
        parameters: ["codigoParlamentar"]
      - path: "/senador/{codigoParlamentar}/votacoes"
        method: "GET"
        description: "Votações de um senador"
        parameters: ["codigoParlamentar","sigla","tramitando","tipo","tipoSessao","ano","primeiro"]
      - path: "/materia/{codigoMateria}"
        method: "GET"
        description: "Obter matéria por código"
        parameters: ["codigoMateria"]
      - path: "/materia/atualizadas"
        method: "GET"
        description: "Listar matérias atualizadas"
        parameters: ["numdias","sigla","numero","ano","codigo","codAssuntoGeral","codAssuntoEspecifico","alteracao"]
      - path: "/comissao/lista/{tipo}"
        method: "GET"
        description: "Listar comissões (permanente, temporaria, cpi)"
        parameters: ["tipo"]
      - path: "/comissao/{sigla}/documentos"
        method: "GET"
        description: "Documentos de comissão"
        parameters: ["sigla","dataInicio","dataFim"]
      - path: "/agendareuniao/{data}"
        method: "GET"
        description: "Agenda de reuniões por data"
        parameters: ["data"]
      - path: "/agendareuniao/atual/iCal"
        method: "GET"
        description: "Agenda atual em iCal"
      - path: "/plenario/lista/votacao/{data}"
        method: "GET"
        description: "Votações plenárias por data"
        parameters: ["data"]
      - path: "/dados/ListaAssuntos.xml"
        method: "GET"
        description: "Assuntos de matéria (XML)"
      - path: "/dados/ListaClassificacoesMateria.xml"
        method: "GET"
        description: "Classificações de matéria (XML)"
      - path: "/dados/ListaTiposEmenda.xml"
        method: "GET"
        description: "Tipos de emenda (XML)"
      - path: "/dados/ListaTiposNatureza.xml"
        method: "GET"
        description: "Tipos de natureza (XML)"
      - path: "/dados/ListaTiposDecisao.xml"
        method: "GET"
        description: "Tipos de decisão (XML)"
      - path: "/dados/ListaDestinos.xml"
        method: "GET"
        description: "Destinos (XML)"
      - path: "/dados/ListaPartidos.xml"
        method: "GET"
        description: "Partidos dos parlamentares (XML)"
      - path: "/legislacao/termos"
        method: "GET"
        description: "Termos de legislação (XML)"

  portal_transparencia:
    name: "Portal da Transparência"
    base_url: "http://www.transparencia.gov.br/api-de-dados"
    enabled: true
    token_required: true
    token_header: "chave-api-dados"
    endpoints:
      - path: "/orgaos-siafi"
        method: "GET"
        description: "Lista órgãos SIAFI"
      - path: "/despesas/por-orgao"
        method: "GET"
        description: "Despesas por órgão"
        parameters: ["mesAno","codigoOrgao","pagina"]
      - path: "/servidores"
        method: "GET"
        description: "Dados de servidores"
        parameters: ["codigoOrgao","mesAno","pagina"]

  ibge:
    name: "API IBGE"
    base_url: "https://servicodados.ibge.gov.br/api/v1"
    enabled: true
    endpoints:
      - path: "/localidades/estados"
        method: "GET"
        description: "Lista estados"
      - path: "/localidades/municipios"
        method: "GET"
        description: "Lista municípios"
        parameters: ["UF"]
      - path: "/censos/nomes/ranking"
        method: "GET"
        description: "Ranking de nomes"

  banco_central:
    name: "API Banco Central"
    base_url: "https://api.bcb.gov.br/dados/serie/bcdata.sgs"
    enabled: true
    endpoints:
      - path: "/{codigo}/dados"
        method: "GET"
        description: "Dados de série temporal"
        parameters: ["codigo","dataInicial","dataFinal"]

  inep:
    name: "API INEP"
    base_url: "https://api.inep.gov.br"
    enabled: true
    token_required: true
    endpoints:
      - path: "/indicadores-educacionais"
        method: "GET"
        description: "Indicadores educacionais"
      - path: "/censo-escolar"
        method: "GET"
        description: "Dados do censo escolar"

  ans:
    name: "API ANS"
    base_url: "http://www.ans.gov.br/anstabnet/cgi-bin/dh"
    enabled: true
    endpoints:
      - path: "/operadoras"
        method: "GET"
        description: "Lista operadoras de planos de saúde"

  aneel:
    name: "API ANEEL"
    base_url: "https://www.aneel.gov.br/dados/api"
    enabled: true
    endpoints:
      - path: "/tarifas"
        method: "GET"
        description: "Tarifas de energia elétrica"

authentication:
  portal_transparencia:
    type: "api_key"
    header: "chave-api-dados"
    env_var: "PORTAL_TRANSPARENCIA_API_KEY"
  inep:
    type: "bearer_token"
    env_var: "INEP_API_TOKEN"

cache:
  type: "redis"
  host: "localhost"
  port: 6379
  db: 0
  prefix: "api_search_"
  default_ttl: 3600

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/api_search.log"
  max_size: "10MB"
  backup_count: 5

web_interface:
  enabled: true
  host: "0.0.0.0"
  port: 8000
  debug: false
  title: "Sistema de Buscas - APIs Oficiais BR"
  description: "Interface para busca integrada em APIs governamentais brasileiras"

search_categories:
  governo:
    name: "Dados Governamentais"
    description: "Informações sobre governo, legislativo e executivo"
    apis: ["camara_deputados","senado_federal","portal_transparencia"]
  economia:
    name: "Dados Econômicos"
    description: "Informações econômicas e financeiras"
    apis: ["banco_central","receita_federal","brasil_api"]
  geografia:
    name: "Dados Geográficos"
    description: "Informações sobre localidades e geografia"
    apis: ["ibge","brasil_api"]
  educacao:
    name: "Educação"
    description: "Dados educacionais e indicadores"
    apis: ["inep"]
  regulacao:
    name: "Agências Reguladoras"
    description: "Dados de agências reguladoras"
    apis: ["ans","aneel"]
  geral:
    name: "Dados Gerais"
    description: "Outros dados governamentais"
    apis: ["dados_gov"]

search_mapping:
  deputado: ["camara_deputados"]
  senador: ["senado_federal"]
  lei: ["camara_deputados","senado_federal"]
  proposicao: ["camara_deputados","senado_federal"]
  orcamento: ["portal_transparencia"]
  despesa: ["portal_transparencia"]
  servidor: ["portal_transparencia"]
  cnpj: ["receita_federal","brasil_api"]
  cep: ["brasil_api"]
  municipio: ["ibge"]
  estado: ["ibge"]
  educacao: ["inep"]
  selic: ["banco_central"]
  inflacao: ["banco_central","brasil_api"]
  plano_saude: ["ans"]
  energia: ["aneel"]

rate_limiting:
  default:
    requests_per_minute: 60
    requests_per_hour: 1000
  por_api:
    brasil_api:
      requests_per_minute: 200
    camara_deputados:
      requests_per_minute: 120
    portal_transparencia:
      requests_per_minute: 100

export:
  formats: ["json","csv","pdf"]
  max_results: 1000
  pdf_template: "templates/report.html"

monitoring:
  enabled: true
  metrics_endpoint: "/metrics"
  health_endpoint: "/health"

development:
  auto_reload: true
  show_sql: false
  mock_apis: false
