      parameters: [id]
      category: deputados

    - path: /deputados/{id}/despesas
      method: GET
      description: Despesas de deputado
      parameters: [id, ano, mes, cnpjCpfFornecedor]
      category: despesas

    - path: /deputados/{id}/discursos
      method: GET
      description: Discursos de deputado
      parameters: [id, dataInicio, dataFim, pagina, itens]
      category: discursos

    - path: /deputados/relatorioQuadroResumo
      method: GET
      description: Resumo por partido e estado
      parameters: [codPartido, siglaUf, dataInicio, dataFim]
      category: relatórios

    - path: /deputados/emexercicio
      method: GET
      description: Deputados em exercício
      parameters: []
      category: deputados

    - path: /proposicoes
      method: GET
      description: Lista proposições
      parameters: [sigla, numero, ano, autoria, palavrasChave, pagina, itens]
      category: proposicoes

    - path: /proposicoes/{id}
      method: GET
      description: Proposição por ID
      parameters: [id]
      category: proposicoes

    - path: /proposicoes/{id}/tramitacoes
      method: GET
      description: Tramitações de proposição
      parameters: [id, pagina, itens]
      category: proposicoes

    - path: /proposicoes/{id}/votacoes
      method: GET
      description: Votações de proposição
      parameters: [id, pagina, itens]
      category: proposicoes

    - path: /votacoes
      method: GET
      description: Lista votações
      parameters: [dataInicio, dataFim, tipo, pagina, itens]
      category: votacoes

    - path: /votacoes/{id}
      method: GET
      description: Votação por ID
      parameters: [id]
      category: votacoes

    - path: /plenarinho/votacoes
      method: GET
      description: Votações no Plenário
      parameters: [data]
      category: votacoes

    - path: /partidos
      method: GET
      description: Lista partidos
      parameters: []
      category: partidos

    - path: /frentes
      method: GET
      description: Listagem de frentes parlamentares
      parameters: []
      category: frentes

    - path: /frentes/{id}
      method: GET
      description: Frente parlamentar por ID
      parameters: [id]
      category: frentes

    - path: /orgaos
      method: GET
      description: Lista órgãos da Câmara
      parameters: []
      category: orgaos

    - path: /orgaos/{id}/deputados
      method: GET
      description: Deputados por órgão
      parameters: [id, pagina, itens]
      category: orgaos

    - path: /comissoes
      method: GET
      description: Lista comissões
      parameters: [sigla, tipo, pagina, itens]
      category: comissoes

    - path: /comissoes/{id}
      method: GET
      description: Comissão por ID
      parameters: [id]
      category: comissoes

    - path: /deputados/{id}/frentes
      method: GET
      description: Frentes de deputado
      parameters: [id]
      category: frentes

    - path: /deputados/{id}/comissoes
      method: GET
      description: Comissões de deputado
      parameters: [id]
      category: comissoes

    - path: /deputados/{id}/orgaos
      method: GET
      description: Órgãos de deputado
      parameters: [id]
      category: orgaos

    - path: /referencias/temas
      method: GET
      description: Temas de proposições
      parameters: []
      category: referencias

    - path: /referencias/tiposProposicao
      method: GET
      description: Tipos de proposição
      parameters: []
      category: referencias

    - path: /referencias/siglasPartidos
      method: GET
      description: Siglas de partidos
      parameters: []
      category: referencias

    - path: /referencias/siglasUfs
      method: GET
      description: Siglas de UFs
      parameters: []
      category: referencias


  senado_federal:
    name: API Senado Federal
    base_url: https://legis.senado.leg.br/dadosabertos
    enabled: true
    token_required: false
    rate_limit:
      requests_per_minute: 100
      burst_limit: 25
    endpoints:
      - path: /senador/lista/atual
        method: GET
        description: Senadores em exercício
      - path: /senador/{codigoParlamentar}
        method: GET
        description: Senador por código
        parameters: [codigoParlamentar]
      - path: /senador/{codigoParlamentar}/votacoes
        method: GET
        description: Votações de senador
        parameters: [codigoParlamentar, ano]
      - path: /materia/{codigoMateria}
        method: GET
        description: Matéria por código
        parameters: [codigoMateria]
      - path: /materia/atualizadas
        method: GET
        description: Matérias atualizadas
        parameters: [numdias, sigla, numero, ano]
      - path: /comissao/lista/{tipo}
        method: GET
        description: Lista comissões
        parameters: [tipo]
      - path: /plenario/lista/votacao/{data}
        method: GET
        description: Votações plenárias
        parameters: [data]
      - path: /dados/ListaPartidos.xml
        method: GET
        description: Lista partidos (XML)
      - path: /legislacao/termos
        method: GET
        description: Termos de legislação

  dados_gov:
    name: Portal Brasileiro de Dados Abertos
    base_url: https://dados.gov.br/api/3
    enabled: true
    token_required: true
    token_header: Authorization
    token_prefix: Bearer
    rate_limit:
      requests_per_minute: 60
      burst_limit: 20
    endpoints:
      - path: /action/package_list
        method: GET
        description: Lista conjuntos de dados
      - path: /action/package_show
        method: GET
        description: Detalhes de conjunto
        parameters: [id]
      - path: /action/package_search
        method: GET
        description: Busca conjuntos
        parameters: [q, rows, start, sort]
      - path: /action/organization_list
        method: GET
        description: Lista organizações
      - path: /action/group_list
        method: GET
        description: Lista grupos/temas
      - path: /action/tag_list
        method: GET
        description: Lista tags

  ibge:
    name: API IBGE
    base_url: https://servicodados.ibge.gov.br/api/v1
    enabled: true
    token_required: false
    rate_limit:
      requests_per_minute: 200
      burst_limit: 50
    endpoints:
      - path: /localidades/estados
        method: GET
        description: Lista estados
        parameters: [orderBy, view]
      - path: /localidades/estados/{uf}
        method: GET
        description: Estado por UF
        parameters: [uf]
      - path: /localidades/municipios
        method: GET
        description: Lista municípios
        parameters: [UF, orderBy, view]
      - path: /localidades/municipios/{id}
        method: GET
        description: Município por ID
        parameters: [id]
      - path: /localidades/distritos
        method: GET
        description: Lista distritos
        parameters: [orderBy, view]
      - path: /localidades/regioes
        method: GET
        description: Lista regiões
        parameters: [orderBy, view]
      - path: /localidades/paises
        method: GET
        description: Lista países
        parameters: [orderBy, view, lang]
      - path: /censos/nomes/ranking
        method: GET
        description: Ranking de nomes
        parameters: [nome, sexo, decada]
      - path: /censos/nomes/{nome}
        method: GET
        description: Frequência de nome
        parameters: [nome, sexo]

  banco_central:
    name: APIs Banco Central
    base_url: https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/odata
    enabled: true
    token_required: false
    rate_limit:
      requests_per_minute: 60
      burst_limit: 15
    endpoints:
      - path: /Moedas
        method: GET
        description: Lista moedas disponíveis
      - path: /CotacaoMoedaDia(moeda=@moeda,dataCotacao=@data)
        method: GET
        description: Cotação de moeda por data
        parameters: [moeda, data]
        example: /CotacaoMoedaDia(moeda='USD',dataCotacao='2025-09-09')
      - path: /CotacaoMoedaPeriodo(moeda=@moeda,dataInicial=@dataInicial,dataFinalCotacao=@dataFinal)
        method: GET
        description: Cotações por período
        parameters: [moeda, dataInicial, dataFinal]
        example: /CotacaoMoedaPeriodo(moeda='USD',dataInicial='2025-09-01',dataFinalCotacao='2025-09-09')
    alternative_endpoints:
      sgs: https://api.bcb.gov.br/dados/serie/bcdata.sgs
      pix: https://dadosabertos.bcb.gov.br/dataset/estatisticas-pix

# === CONFIGURAÇÕES MANTIDAS ===
authentication:
  portal_transparencia:
    type: api_key
    header: chave-api-dados
    env_var: PORTAL_TRANSPARENCIA_API_KEY
    registration_url: https://portaldatransparencia.gov.br/api-de-dados/cadastrar-email
  dados_gov:
    type: bearer_token
    header: Authorization
    env_var: DADOS_GOV_API_TOKEN

search_mapping:
  # Mapeamentos existentes mantidos
  deputado: [camara_deputados]
  senador: [senado_federal]
  congresso: [camara_deputados, senado_federal]
  lei: [camara_deputados, senado_federal]
  proposicao: [camara_deputados, senado_federal]
  votacao: [camara_deputados, senado_federal]
  orcamento: [portal_transparencia]
  despesa: [portal_transparencia]
  gastos: [portal_transparencia]
  servidor: [portal_transparencia]
  licitacao: [portal_transparencia]
  transparencia: [portal_transparencia]
  cnpj: [brasil_api]
  cep: [brasil_api]
  ddd: [brasil_api]
  municipio: [ibge, brasil_api]
  estado: [ibge, brasil_api]
  cidade: [ibge, brasil_api]
  geografia: [ibge]
  nome: [ibge]
  banco: [brasil_api]
  cotacao: [banco_central]
  dolar: [banco_central]
  cambio: [banco_central]
  selic: [banco_central]
  pix: [banco_central, brasil_api]
  dados: [dados_gov]
  dataset: [dados_gov]
  
  # Novos mapeamentos específicos do Portal da Transparência
  bolsa_familia: [portal_transparencia]
  auxilio_emergencial: [portal_transparencia]
  auxilio_brasil: [portal_transparencia]
  bpc: [portal_transparencia]
  beneficios: [portal_transparencia]
  sancoes: [portal_transparencia]
  ceis: [portal_transparencia]
  cnep: [portal_transparencia]
  contratos: [portal_transparencia]
  convenios: [portal_transparencia]
  cartoes: [portal_transparencia]
  emendas: [portal_transparencia]
  imoveis: [portal_transparencia]
  renuncias: [portal_transparencia]
  notas_fiscais: [portal_transparencia]
  peps: [portal_transparencia]

cache:
  type: redis
  host: localhost
  port: 6379
  db: 0
  prefix: api_search_
  default_ttl: 3600

logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: logs/api_search.log
  max_size: 10MB
  backup_count: 5

web_interface:
  enabled: true
  host: 0.0.0.0
  port: 8000
  debug: false
  title: Sistema de Buscas - APIs Oficiais BR v3.0 COMPLETO
  description: Interface consolidada com TODOS os endpoints do Portal da Transparência e demais APIs governamentais

export:
  formats: [json, csv, pdf]
  max_results: 1000
  pdf_template: templates/report.html

monitoring:
  enabled: true
  metrics_endpoint: /metrics
  health_endpoint: /health
